# Markdownlint configuration
default: true

# MD013/line-length: Line length
# Relaxing to 120 chars to match modern standards and avoid excessive wrapping
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD033/no-inline-html: Inline HTML
# Allowed for badges and complex formatting
MD033:
  allowed_elements: ["div", "span", "img", "br", "p", "a"]
