name: "Validate Context Limits"
description: "Validates that instruction files adhere to token limits per provider."
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: pip install -e ".[dev]"

    - name: Run tests
      shell: bash
      run: python -m pytest tests/ -v

    - name: Run validation script
      shell: bash
      run: python scripts/validate_context_limits.py
