name: "Run Tests"
description: "Runs the project test suite."
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      shell: bash
      run: pip install -e ".[dev]"

    - name: Run pytest
      shell: bash
      run: python -m pytest tests/ -v
